/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.Controladora;
import Modelo.Combo;
import Modelo.Comida;
import Modelo.Pedido;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Set;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Scarlet
 */
public class CobroOrden extends javax.swing.JFrame {
    Controladora micontrol;
    
    List<String> mesasOcupadasEnSistema;
    
    String[] nombres = {};
    List<Integer> codigos = new ArrayList<>();
    
    Set <Pedido> pedidos;
        
    /**
     * Creates new form CobroOrden
     */
    public CobroOrden() {
        initComponents();
    }
    
    public void cargarOrdenes(){
        pedidos = micontrol.getPedidos();
                
        codigos = new ArrayList<>();
        
        DefaultTableModel modelT = (DefaultTableModel) listadoDeOrdenes.getModel();
        modelT.setRowCount(0);
        for(Pedido pedido:pedidos){
            codigos.add(pedido.getCodigo());
            modelT.addRow(new Object[]{pedido.getCodigo(), pedido.getMesa(), pedido.getMesero().conseguirNombreCompleto()/*, pedido.getFechaPedido()*/, pedido.getPrecioTotal(), pedido.getOrdenCobrada()});
        }
        
        ComboBoxMetodosDePagos.removeAllItems();
        ComboBoxMetodosDePagos.setModel(new DefaultComboBoxModel<>(micontrol.getMetodosDePago()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        salirMenuCobroDeOrden = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listadoDeOrdenes = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        CampoIVAOrden = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        NombreClienteAPagar = new javax.swing.JTextField();
        PrecioFinal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        pagarOrden = new javax.swing.JButton();
        ComboBoxMetodosDePagos = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("El Tajo");

        salirMenuCobroDeOrden.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        salirMenuCobroDeOrden.setText("SALIR");
        salirMenuCobroDeOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirMenuCobroDeOrdenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(salirMenuCobroDeOrden)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel5)
                .addGap(137, 137, 137)
                .addComponent(salirMenuCobroDeOrden)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 255, 204));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setText("CAJERO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 2, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cobro de orden");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        jLabel4.setText("Metodo de Pago:");

        listadoDeOrdenes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo Pedido", "Mesa", "Mesero", "Fecha", "Costo", "orden activa?"
            }
        ));
        listadoDeOrdenes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                listadoDeOrdenesFocusGained(evt);
            }
        });
        listadoDeOrdenes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listadoDeOrdenesMouseClicked(evt);
            }
        });
        listadoDeOrdenes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                listadoDeOrdenesKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(listadoDeOrdenes);

        jLabel6.setText("Nombre cliente");
        jLabel6.setToolTipText("");

        CampoIVAOrden.setEditable(false);
        CampoIVAOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoIVAOrdenActionPerformed(evt);
            }
        });

        jLabel7.setText("Precio final");
        jLabel7.setToolTipText("");

        NombreClienteAPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreClienteAPagarActionPerformed(evt);
            }
        });

        PrecioFinal.setEditable(false);
        PrecioFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecioFinalActionPerformed(evt);
            }
        });

        jLabel8.setText("IVA (16%)");
        jLabel8.setToolTipText("");

        pagarOrden.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        pagarOrden.setText("REGISTRAR VENTA");
        pagarOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagarOrdenActionPerformed(evt);
            }
        });

        ComboBoxMetodosDePagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxMetodosDePagosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                                .addComponent(ComboBoxMetodosDePagos, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(NombreClienteAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pagarOrden, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(CampoIVAOrden, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PrecioFinal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(247, 247, 247))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ComboBoxMetodosDePagos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(NombreClienteAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoIVAOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PrecioFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(pagarOrden)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirMenuCobroDeOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirMenuCobroDeOrdenActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_salirMenuCobroDeOrdenActionPerformed

    private void listadoDeOrdenesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_listadoDeOrdenesFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_listadoDeOrdenesFocusGained

    private void listadoDeOrdenesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listadoDeOrdenesMouseClicked
        // TODO add your handling code here:
        if(listadoDeOrdenes.getSelectedRow() != -1){
            Pedido pedido_seleccionado = (Pedido)micontrol.filtrarPedidoPorCodigo(
                    this.pedidos,
                    codigos.get(listadoDeOrdenes.getSelectedRow())
            );    
            
            double iva = pedido_seleccionado.getPrecioTotal()*0.16;
            CampoIVAOrden.setText( iva+"");
            PrecioFinal.setText((pedido_seleccionado.getPrecioTotal()+iva)+"");
        }

    }//GEN-LAST:event_listadoDeOrdenesMouseClicked

    private void listadoDeOrdenesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_listadoDeOrdenesKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_listadoDeOrdenesKeyPressed

    private void CampoIVAOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoIVAOrdenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoIVAOrdenActionPerformed

    private void NombreClienteAPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreClienteAPagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreClienteAPagarActionPerformed

    private void PrecioFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecioFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrecioFinalActionPerformed

    private void pagarOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagarOrdenActionPerformed
        // TODO add your handling code here:
        if(listadoDeOrdenes.getSelectedRow() != -1 && !NombreClienteAPagar.getText().isBlank()){
            Pedido pedido_seleccionado = (Pedido)micontrol.filtrarPedidoPorCodigo(
                    this.pedidos,
                    codigos.get(listadoDeOrdenes.getSelectedRow())
            );
            if(pedido_seleccionado.getOrdenCobrada()){ JOptionPane.showMessageDialog(rootPane, "el pedido seleccionado ya ha sido pagado");}
            else{
                micontrol.crearVenta(pedido_seleccionado, NombreClienteAPagar.getText(), ComboBoxMetodosDePagos.getSelectedItem().toString(), LocalDateTime.now());
                JOptionPane.showMessageDialog(rootPane, "Venta registrada exitosamente");
                cargarOrdenes();
            }            
        }else{            
            if(listadoDeOrdenes.getSelectedRow() == -1) JOptionPane.showMessageDialog(rootPane, "debe seleccionar la orden a pagar");
            if(NombreClienteAPagar.getText().isBlank()) JOptionPane.showMessageDialog(rootPane, "debe indicar el nombre del cliente a pagar");
        }
    }//GEN-LAST:event_pagarOrdenActionPerformed

    private void ComboBoxMetodosDePagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxMetodosDePagosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxMetodosDePagosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CobroOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CobroOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CobroOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CobroOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CobroOrden().setVisible(true);
            }
        });
    }
     public void setMicontrol(Controladora micontrol) {
        this.micontrol = micontrol;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CampoIVAOrden;
    private javax.swing.JComboBox<String> ComboBoxMetodosDePagos;
    private javax.swing.JTextField NombreClienteAPagar;
    private javax.swing.JTextField PrecioFinal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable listadoDeOrdenes;
    private javax.swing.JButton pagarOrden;
    private javax.swing.JButton salirMenuCobroDeOrden;
    // End of variables declaration//GEN-END:variables
}
