/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.Controladora;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import Modelo.Categoria;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Scarlet
 */
public class RegistroPlato extends javax.swing.JFrame {
    Controladora micontrol;
    String[] nombres = {};
    int[] codigos = {};
    
    List<String> nombre_comidas;
    List<Integer> codigo_comidas;
    List<String> precio_comidas;
    List<String> descripcion_comidas;
    List<String> categoria_comidas;
    
    int[] codigos_categoria = {};
    String[] listaCategoriasGuardadas = {};
    /**
     * Creates new form RegistroPlato
     */
    public RegistroPlato() {
        initComponents();
    }
    
    public void cargarComida(){
        nombre_comidas = micontrol.filtrarComidasPorNombre();
        codigo_comidas = micontrol.getComidasPorCodigo();        
        precio_comidas = micontrol.filtrarComidasPorPrecio();
        descripcion_comidas = micontrol.filtrarComidasPorDescripcion();
        categoria_comidas = micontrol.filtrarComidasPorCategoria();
        
        DefaultTableModel modelT = (DefaultTableModel) listadoPlatos.getModel();                                                  
        
        codigos = new int[codigo_comidas.size()];
        
        modelT.setRowCount(0);
        for (int i = 0; i < codigos.length; i++) {
            codigos[i] = codigo_comidas.get(i);
            modelT.addRow(new Object[]{nombre_comidas.get(i), descripcion_comidas.get(i), precio_comidas.get(i),  categoria_comidas.get(i)});
        }
    }
    
    public void cargarCategorias(){
        List<String> nombre_categorias = micontrol.filtrarCategoriasPorNombre();
        List<Integer> codigo_categorias = micontrol.getCategoriasPorCodigo();
        
        codigos_categoria = new int[codigo_categorias.size()];
        for (int i = 0; i < codigos_categoria.length; i++) {
            codigos_categoria[i] = codigo_categorias.get(i);
        }
        nombres = nombre_categorias.toArray(nombres);
        
        listaCategoria.removeAllItems();
        listaCategoria.setModel(new DefaultComboBoxModel<>(nombre_categorias.toArray(nombres)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        salirMenuRegPlato = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nombrePlato = new javax.swing.JTextField();
        descripcionPlato = new javax.swing.JTextField();
        precioPlato = new javax.swing.JTextField();
        listaCategoria = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        guardarPlato = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listadoPlatos = new javax.swing.JTable();
        modificarPlato = new javax.swing.JButton();
        eliminarPlato = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 0));
        jLabel2.setText("El Tajo");

        salirMenuRegPlato.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        salirMenuRegPlato.setText("SALIR");
        salirMenuRegPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirMenuRegPlatoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(salirMenuRegPlato)
                    .addComponent(jLabel2))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addGap(199, 199, 199)
                .addComponent(salirMenuRegPlato)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("CHEF");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(200, 200, 200))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 2, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Registro de Plato");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(125, 125, 125))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jLabel4.setText("Nombre del Plato:");

        jLabel5.setText("Descripcion del Plato:");

        jLabel7.setText("Categoria del plato");

        nombrePlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombrePlatoActionPerformed(evt);
            }
        });

        listaCategoria.setName(""); // NOI18N
        listaCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaCategoriaActionPerformed(evt);
            }
        });

        jLabel8.setText("Precio del plato:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(51, 51, 51)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descripcionPlato)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombrePlato, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(listaCategoria, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(precioPlato, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)))
                        .addGap(0, 147, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(nombrePlato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(descripcionPlato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel8))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(precioPlato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(listaCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        guardarPlato.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        guardarPlato.setText("GUARDAR PLATO");
        guardarPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarPlatoActionPerformed(evt);
            }
        });

        listadoPlatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Descripcion", "Precio", "Categoria"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        listadoPlatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listadoPlatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listadoPlatos);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        modificarPlato.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        modificarPlato.setText("MODIFICAR PLATO");
        modificarPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarPlatoActionPerformed(evt);
            }
        });

        eliminarPlato.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        eliminarPlato.setText("ELIMINAR PLATO");
        eliminarPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarPlatoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 9, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(guardarPlato)
                        .addGap(18, 18, 18)
                        .addComponent(modificarPlato)
                        .addGap(18, 18, 18)
                        .addComponent(eliminarPlato)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(guardarPlato)
                        .addComponent(modificarPlato))
                    .addComponent(eliminarPlato, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirMenuRegPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirMenuRegPlatoActionPerformed
        micontrol.cerrarRegistroPlato();    // TODO add your handling code here:
    }//GEN-LAST:event_salirMenuRegPlatoActionPerformed

    private void nombrePlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombrePlatoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_nombrePlatoActionPerformed

    private void guardarPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarPlatoActionPerformed
       // TODO add your handling code here:
       if(listaCategoria.getItemCount() != 0 && !nombrePlato.getText().isEmpty() && !nombrePlato.getText().isBlank() && !precioPlato.getText().isEmpty() && !precioPlato.getText().isBlank()){
            Categoria categoria_seleccionada_por_usuario = (Categoria)micontrol.filtrarCategoriaPorCodigo(micontrol.getCategorias(), codigos_categoria[listaCategoria.getSelectedIndex()]);
            micontrol.crearComida(nombrePlato.getText(),descripcionPlato.getText() , precioPlato.getText(), categoria_seleccionada_por_usuario );
            cargarComida();
       }else{
           if(listaCategoria.getItemCount() == 0) JOptionPane.showMessageDialog(rootPane, "debe registrar alguna categoria primero");
           if(nombrePlato.getText().isBlank()) JOptionPane.showMessageDialog(rootPane, "debe ingresar un nombre para el plato");
           if(precioPlato.getText().isBlank()) JOptionPane.showMessageDialog(rootPane, "debe ingresar un precio para el plato");
       }
    }//GEN-LAST:event_guardarPlatoActionPerformed

    private void modificarPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarPlatoActionPerformed
        // TODO add your handling code here:        
        if(listaCategoria.getItemCount() != 0 && listadoPlatos.getRowCount() != 0){
            try{
                Categoria categoria_seleccionada_por_usuario = (Categoria)micontrol.filtrarCategoriaPorCodigo(micontrol.getCategorias(), codigos_categoria[listaCategoria.getSelectedIndex()]);
                micontrol.modificarComida(nombrePlato.getText(),descripcionPlato.getText() , precioPlato.getText(), categoria_seleccionada_por_usuario, codigos[listadoPlatos.getSelectedRow()] );
                cargarComida();
            }catch(Exception e){
                //este catch es necesario ya que ocurre un error fuera del index si el usuario selecciona un elemento a modificar y luego realiza la creacion/eliminacion de algun elemento, antes de modificarlo
                //esto causa que el numero de elementos disminuya y pueda ocurrir un error fuera de indice. ej: si queriamos modificar el elemento 5, pero tras eliminar un elemento ahora hay 4, entonces al tratar de acceder al 5 todo explota
                JOptionPane.showMessageDialog(rootPane, "error al modificar el plato, por favor repita los pasos e intente de nuevo, error:"+ e.getMessage());
            }
            
        }else{
            if(listadoPlatos.getRowCount()== 0){ JOptionPane.showMessageDialog(rootPane, "debe seleccionar el plato que desea modificar ");}
            if(listaCategoria.getItemCount()== 0){ JOptionPane.showMessageDialog(rootPane, "debe registrar alguna categoria primero ");}            
        }
    }//GEN-LAST:event_modificarPlatoActionPerformed

    private void eliminarPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarPlatoActionPerformed
        // TODO add your handling code here:
        if(listadoPlatos.getRowCount() != 0 &&  listadoPlatos.getSelectedRow() != -1){
            micontrol.eliminarComida(codigos[listadoPlatos.getSelectedRow()]);
            cargarComida();            
        }else{
            JOptionPane.showMessageDialog(rootPane, "debe seleccionar la plato a eliminar");
        }
    }//GEN-LAST:event_eliminarPlatoActionPerformed

    private void listaCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listaCategoriaActionPerformed

    private void listadoPlatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listadoPlatosMouseClicked
        // TODO add your handling code here:
        if(listadoPlatos.getSelectedRow()!=-1){
            nombrePlato.setText(nombre_comidas.get(listadoPlatos.getSelectedRow()));
            precioPlato.setText(precio_comidas.get(listadoPlatos.getSelectedRow())  );      
            descripcionPlato.setText(descripcion_comidas.get( listadoPlatos.getSelectedRow()));
            listaCategoria.setSelectedItem(categoria_comidas.get(listadoPlatos.getSelectedRow())); ;
        }
    }//GEN-LAST:event_listadoPlatosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroPlato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroPlato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroPlato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroPlato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroPlato().setVisible(true);
            }
        });
    }
     public void setMicontrol(Controladora micontrol) {
        this.micontrol = micontrol;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField descripcionPlato;
    private javax.swing.JButton eliminarPlato;
    private javax.swing.JButton guardarPlato;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> listaCategoria;
    private javax.swing.JTable listadoPlatos;
    private javax.swing.JButton modificarPlato;
    private javax.swing.JTextField nombrePlato;
    private javax.swing.JTextField precioPlato;
    private javax.swing.JButton salirMenuRegPlato;
    // End of variables declaration//GEN-END:variables
}
