/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.Controladora;
import Modelo.Combo;
import Modelo.Comida;
import java.util.List;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Scarlet
 */
public class RegistroMenuDelDia extends javax.swing.JFrame {
    Controladora micontrol;
    String[] nombres = {};
    int[] codigos = {};
    
    List<String> nombre_menus;
    List<Integer> codigo_menus;
    
    List<String> nombre_combos;
    List<Integer> codigo_combos;
    
    List<String> nombre_comidas;
    List<Integer> codigo_comidas;
    
    List<String> comidas_por_cada_menu;  
    List<String> combos_por_cada_menu;
    
    /**
     * Creates new form RegistroMenuDelDia
     */
    public RegistroMenuDelDia() {
        initComponents();
    }

     public void cargarMenu(){
        nombre_menus = micontrol.filtrarMenuPorNombre();
        codigo_menus = micontrol.getMenuPorCodigo();
        
        nombre_combos = micontrol.filtrarCombosPorNombre();
        codigo_combos = micontrol.getCombosPorCodigo();  

        nombre_comidas = micontrol.filtrarComidasPorNombre();        
        codigo_comidas = micontrol.getComidasPorCodigo();
                
        comidas_por_cada_menu = micontrol.getComidasDelMenu();
        combos_por_cada_menu = micontrol.getStringCombosDelMenu(); 
        
        DefaultTableModel modelT = (DefaultTableModel) listadoDeCombos.getModel();                                                  
        
        codigos = new int[nombre_menus.size()];
        
        modelT.setRowCount(0);
        for (int iteradorCombos = 0; iteradorCombos < codigos.length; iteradorCombos++) {
            codigos[iteradorCombos] = codigo_menus.get(iteradorCombos);
            modelT.addRow(new Object[]{nombre_menus.get(iteradorCombos), combos_por_cada_menu.get(iteradorCombos) , comidas_por_cada_menu.get(iteradorCombos)});
        }
               
        listaCombosDisponibles.removeAllItems();
        listaCombosDisponibles.setModel(new DefaultComboBoxModel<>(nombre_combos.toArray(nombres)));
        
        listaPlatoDisponibles.removeAllItems();
        listaPlatoDisponibles.setModel(new DefaultComboBoxModel<>(nombre_comidas.toArray(nombres)));
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        salirMenuDelDia = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        listaPlatoDisponibles = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        listaPlatoAgregados = new javax.swing.JComboBox<>();
        listaCombosAgregados = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        guardarCombo = new javax.swing.JButton();
        eliminarCombo = new javax.swing.JButton();
        listaCombosDisponibles = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        listadoDeCombos = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        nombreMenu = new javax.swing.JTextField();
        AgregarPlato = new javax.swing.JButton();
        RemoverPlato = new javax.swing.JButton();
        AgregarCombo = new javax.swing.JButton();
        RemoverCombo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 0));
        jLabel2.setText("El Tajo");

        salirMenuDelDia.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        salirMenuDelDia.setText("SALIR");
        salirMenuDelDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirMenuDelDiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(salirMenuDelDia)
                    .addComponent(jLabel2))
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel2)
                .addGap(181, 181, 181)
                .addComponent(salirMenuDelDia)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("CHEF");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(207, 207, 207))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 2, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Menu del Dia");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(156, 156, 156))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jLabel4.setText("Plastos agregados al menu :");

        listaPlatoDisponibles.setName(""); // NOI18N
        listaPlatoDisponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaPlatoDisponiblesActionPerformed(evt);
            }
        });

        jLabel7.setText("Combos Disponible :");

        jLabel5.setText("Combos Agregados al menu :");

        listaPlatoAgregados.setName(""); // NOI18N
        listaPlatoAgregados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaPlatoAgregadosActionPerformed(evt);
            }
        });

        listaCombosAgregados.setName(""); // NOI18N
        listaCombosAgregados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaCombosAgregadosActionPerformed(evt);
            }
        });

        jLabel8.setText("Platos disponibles :");

        guardarCombo.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        guardarCombo.setText("GUARDAR MENU");
        guardarCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarComboActionPerformed(evt);
            }
        });

        eliminarCombo.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        eliminarCombo.setText("ELIMINAR MENU");
        eliminarCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarComboActionPerformed(evt);
            }
        });

        listaCombosDisponibles.setName(""); // NOI18N
        listaCombosDisponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaCombosDisponiblesActionPerformed(evt);
            }
        });

        listadoDeCombos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre  Menu", "Combos(s)", "Plato(s)"
            }
        ));
        listadoDeCombos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                listadoDeCombosFocusGained(evt);
            }
        });
        listadoDeCombos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listadoDeCombosMouseClicked(evt);
            }
        });
        listadoDeCombos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                listadoDeCombosKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(listadoDeCombos);

        jLabel9.setText("Nombre del menu :");

        nombreMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreMenuActionPerformed(evt);
            }
        });

        AgregarPlato.setText("agregar plato");
        AgregarPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarPlatoActionPerformed(evt);
            }
        });

        RemoverPlato.setText("remover plato");
        RemoverPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoverPlatoActionPerformed(evt);
            }
        });

        AgregarCombo.setText("agregar combo");
        AgregarCombo.setToolTipText("");
        AgregarCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarComboActionPerformed(evt);
            }
        });

        RemoverCombo.setText("remover combo");
        RemoverCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoverComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(guardarCombo)
                        .addGap(18, 18, 18)
                        .addComponent(eliminarCombo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listaPlatoDisponibles, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listaCombosAgregados, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listaPlatoAgregados, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listaCombosDisponibles, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RemoverCombo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AgregarCombo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AgregarPlato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RemoverPlato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(98, 98, 98))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(nombreMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(listaCombosDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AgregarCombo))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listaCombosAgregados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(RemoverCombo))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listaPlatoDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(AgregarPlato))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(listaPlatoAgregados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RemoverPlato))
                .addGap(79, 79, 79)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarCombo)
                    .addComponent(eliminarCombo))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirMenuDelDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirMenuDelDiaActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_salirMenuDelDiaActionPerformed

    private void listaPlatoDisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaPlatoDisponiblesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listaPlatoDisponiblesActionPerformed

    private void listaPlatoAgregadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaPlatoAgregadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listaPlatoAgregadosActionPerformed

    private void listaCombosAgregadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaCombosAgregadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listaCombosAgregadosActionPerformed

    private void guardarComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarComboActionPerformed
        // TODO add your handling code here:
        if((listaCombosAgregados.getItemCount() != 0 || listaPlatoAgregados.getItemCount() != 0) && !nombreMenu.getText().isBlank() && !nombreMenu.getText().isEmpty()){

            List<Comida> comidas = new ArrayList<>();
            List<Combo> combos = new ArrayList<>();

            if(listaCombosAgregados.getItemCount() != 0){
                for (int indexCombosAAgregar = 0; indexCombosAAgregar < listaCombosAgregados.getItemCount() ; indexCombosAAgregar++) {
                    int  codigo_combo_a_registrar = codigo_combos.get(nombre_combos.indexOf(listaCombosAgregados.getItemAt(indexCombosAAgregar)));
                    combos.add((Combo)micontrol.filtrarComboPorCodigo(micontrol.getCombos(), codigo_combo_a_registrar));
                }                
            }
            
            if(listaPlatoAgregados.getItemCount() != 0){
                for (int indexPlatosAAgregar = 0; indexPlatosAAgregar < listaPlatoAgregados.getItemCount() ; indexPlatosAAgregar++) {
                    int  codigo_comida_a_registrar = codigo_comidas.get(nombre_comidas.indexOf(listaPlatoAgregados.getItemAt(indexPlatosAAgregar)));
                    comidas.add((Comida)micontrol.filtrarComidaPorCodigo( codigo_comida_a_registrar));
                }
            }
            
            micontrol.crearMenu(nombreMenu.getText(), comidas, combos);
            cargarMenu();
        }else{
            if(listaPlatoAgregados.getItemCount()== 0 && listaCombosAgregados.getItemCount()== 0){ JOptionPane.showMessageDialog(rootPane, "debe registrar algun plato y/o combo primero ");}            
            if(nombreMenu.getText().isEmpty()) JOptionPane.showMessageDialog(rootPane, "debe registrar algun nombre para el menu");
        }
    }//GEN-LAST:event_guardarComboActionPerformed

    private void eliminarComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarComboActionPerformed
        // TODO add your handling code here:
        if( listadoDeCombos.getRowCount() != 0 &&  listadoDeCombos.getSelectedRow() != -1){
            micontrol.eliminarMenu(codigos[listadoDeCombos.getSelectedRow()]);
            cargarMenu();
        }
    }//GEN-LAST:event_eliminarComboActionPerformed

    private void listaCombosDisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaCombosDisponiblesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listaCombosDisponiblesActionPerformed

    private void listadoDeCombosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_listadoDeCombosFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_listadoDeCombosFocusGained

    private void listadoDeCombosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listadoDeCombosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_listadoDeCombosMouseClicked

    private void listadoDeCombosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_listadoDeCombosKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_listadoDeCombosKeyPressed

    private void nombreMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreMenuActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_nombreMenuActionPerformed

    private void AgregarPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarPlatoActionPerformed
        // TODO add your handling code here:
        if(listaPlatoDisponibles.getItemCount()!= 0){
            listaPlatoAgregados.addItem(listaPlatoDisponibles.getSelectedItem().toString());
            listaPlatoAgregados.setSelectedIndex(listaPlatoAgregados.getItemCount()-1);
        }
    }//GEN-LAST:event_AgregarPlatoActionPerformed

    private void RemoverPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoverPlatoActionPerformed
        // TODO add your handling code here:
        if(listaPlatoAgregados.getItemCount()!= 0){
            listaPlatoAgregados.removeItemAt(listaPlatoAgregados.getSelectedIndex());
        }
    }//GEN-LAST:event_RemoverPlatoActionPerformed

    private void AgregarComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarComboActionPerformed
        // TODO add your handling code here:        
        if(listaCombosDisponibles.getItemCount()!= 0){
            listaCombosAgregados.addItem(listaCombosDisponibles.getSelectedItem().toString());
            listaCombosAgregados.setSelectedIndex(listaCombosAgregados.getItemCount()-1);
        }
    }//GEN-LAST:event_AgregarComboActionPerformed

    private void RemoverComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoverComboActionPerformed
        // TODO add your handling code here:
        if(listaCombosAgregados.getItemCount()!= 0){
            listaCombosAgregados.removeItemAt(listaCombosAgregados.getSelectedIndex());
        }
    }//GEN-LAST:event_RemoverComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroMenuDelDia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroMenuDelDia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroMenuDelDia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroMenuDelDia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroMenuDelDia().setVisible(true);
            }
        });
    }
    
     public void setMicontrol(Controladora micontrol) {
        this.micontrol = micontrol;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarCombo;
    private javax.swing.JButton AgregarPlato;
    private javax.swing.JButton RemoverCombo;
    private javax.swing.JButton RemoverPlato;
    private javax.swing.JButton eliminarCombo;
    private javax.swing.JButton guardarCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JComboBox<String> listaCombosAgregados;
    private javax.swing.JComboBox<String> listaCombosDisponibles;
    private javax.swing.JComboBox<String> listaPlatoAgregados;
    private javax.swing.JComboBox<String> listaPlatoDisponibles;
    private javax.swing.JTable listadoDeCombos;
    private javax.swing.JTextField nombreMenu;
    private javax.swing.JButton salirMenuDelDia;
    // End of variables declaration//GEN-END:variables
}
